### Numpy

Numpy is findamental package for all scientific computing in python.
  - Multi Dimensional array
      - 1-D (shape(x,)) x= row (axis 0)
      - 2-D (shape(x,y)) x = row (axis 0), y = column (axis 1)
      - 3-D (shape (x,y,z)) x = axis 0, y = axis 1, z = axis 3

Why use NumPy over List ?
    NumPy is faster than List.
How Faster?
    - Numpy uses fixed type
    - faster to read as it consumes less bytes of memory
    - no type checking when iterating through objects
    - uses contiguous memory
        - can use SIMD (Single Instruction Multiple Data) vector processing
        - Effective Cache Utilization    

### Importing package

In [1]:
import numpy as np 

### Basics ( Creating array, shape, size, data types)

In [11]:
# Creating arrays
array_one = np.array([1,2,3])
print(array_one)

print("------------")

array_two = np.array([[1,2,3],[4,5,6]])
print(array_two)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
#Getting Dimensions of our array
array_two.ndim

2

In [5]:
#Getting shape
array_two.shape

(2, 3)

### Memory and Datatype of NumPy

To check how much memory numpy uses 
    - "array_two.dtpe" - int32
NumPy uses int32 by default but we can change it to lower memory if we know how much memory will need

In [12]:
#Get Type
array_one.dtype

dtype('int32')

We can specify data type when we creat an array

In [13]:
array_one = np.array([1,2,3], dtype='int16')
array_one.dtype

dtype('int16')

In [16]:
#Get Single Element Size of array
# For int16, size will be 2
# for int32, size will be 4
array_one.itemsize

2

In [21]:
# Get Total element of array
array_one.size

3

In [20]:
# Get total size of the array
array_one.nbytes

6

### Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)

In [27]:
# Get Specific element of an array [row index, column index]
# indexing always start at 0
array_two[1,2]

6

In [28]:
# Get Specific Row
array_two[0, :]

array([1, 2, 3])

In [29]:
# Get Specific Column
array_two[:, 1]

array([2, 5])

In [30]:
array_three = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# Getting specific elements from a row [row number, column start index: column end index(exclusive): stepsize]
array_three[0,1:6:2]

array([2, 4, 6])

In [43]:
# Change a specific index value
array_three[1,4] = 44
print(array_three)

print("------------")

#Change value of an entire column
# If we want same number
array_three[:,3] = 99 
# If we want different number
array_three[:,3] = [22,55]

print(array_three)

[[ 1  2  3 22  5  6  7]
 [ 8  9 10 55 44 13 14]]
------------
[[ 1  2  3 22  5  6  7]
 [ 8  9 10 55 44 13 14]]


### 3D Example

In [34]:
array_four = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array_four)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


To get specific element from this array we need to pass the dimension correctly (Outside in Method)
    - array_four[array_no,row_index,column_index]

In [36]:
array_four[0,0,1]

2

In [42]:
# to replace we need to give the sub sequence of same dimension
array_four[0,1,1] = 55
print(array_four)

print("------------")

array_four[:,1,:] = [[12,23],[45,56]] 
print(array_four)

[[[ 1  2]
  [12 55]]

 [[ 5  6]
  [45 56]]]
------------
[[[ 1  2]
  [12 23]]

 [[ 5  6]
  [45 56]]]
