### Numpy

Numpy is findamental package for all scientific computing in python.
  - Multi Dimensional array
      - 1-D (shape(x,)) x= row (axis 0)
      - 2-D (shape(x,y)) x = row (axis 0), y = column (axis 1)
      - 3-D (shape (x,y,z)) x = axis 0, y = axis 1, z = axis 3

Why use NumPy over List ?
    NumPy is faster than List.
How Faster?
    - Numpy uses fixed type
    - faster to read as it consumes less bytes of memory
    - no type checking when iterating through objects
    - uses contiguous memory
        - can use SIMD (Single Instruction Multiple Data) vector processing
        - Effective Cache Utilization    

### Importing package

In [3]:
import numpy as np 

### Basics ( Creating array, shape, size, data types)

In [12]:
# Creating arrays
array_one = np.array([1,2,3])
print(array_one)

print("------------")

array_two = np.array([[1,2,3],[4,5,6]])
print(array_two)

[1 2 3]
------------
[[1 2 3]
 [4 5 6]]


In [4]:
#Getting Dimensions of our array
array_two.ndim

2

In [5]:
#Getting shape
array_two.shape

(2, 3)

### Memory and Datatype of NumPy

To check how much memory numpy uses 
    - "array_two.dtpe" - int32
NumPy uses int32 by default but we can change it to lower memory if we know how much memory will need

In [12]:
#Get Type
array_one.dtype

dtype('int32')

We can specify data type when we creat an array

In [13]:
array_one = np.array([1,2,3], dtype='int16')
array_one.dtype

dtype('int16')

In [16]:
#Get Single Element Size of array
# For int16, size will be 2
# for int32, size will be 4
array_one.itemsize

2

In [21]:
# Get Total element of array
array_one.size

3

In [20]:
# Get total size of the array
array_one.nbytes

6

### Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)

In [27]:
# Get Specific element of an array [row index, column index]
# indexing always start at 0
array_two[1,2]

6

In [28]:
# Get Specific Row
array_two[0, :]

array([1, 2, 3])

In [29]:
# Get Specific Column
array_two[:, 1]

array([2, 5])

In [30]:
array_three = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# Getting specific elements from a row [row number, column start index: column end index(exclusive): stepsize]
array_three[0,1:6:2]

array([2, 4, 6])

In [43]:
# Change a specific index value
array_three[1,4] = 44
print(array_three)

print("------------")

#Change value of an entire column
# If we want same number
array_three[:,3] = 99 
# If we want different number
array_three[:,3] = [22,55]

print(array_three)

[[ 1  2  3 22  5  6  7]
 [ 8  9 10 55 44 13 14]]
------------
[[ 1  2  3 22  5  6  7]
 [ 8  9 10 55 44 13 14]]


### 3D Example

In [34]:
array_four = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array_four)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


To get specific element from this array we need to pass the dimension correctly (Outside in Method)
    - array_four[array_no,row_index,column_index]

In [36]:
array_four[0,0,1]

2

In [42]:
# to replace we need to give the sub sequence of same dimension
array_four[0,1,1] = 55
print(array_four)

print("------------")

array_four[:,1,:] = [[12,23],[45,56]] 
print(array_four)

[[[ 1  2]
  [12 55]]

 [[ 5  6]
  [45 56]]]
------------
[[[ 1  2]
  [12 23]]

 [[ 5  6]
  [45 56]]]


### Initializing Different Types of Array

In [7]:
#All 0's Matrix
np.zeros(2) # will give a vector of 5
np.zeros((2,3)) # 2 * 3 Matrix
np.zeros((2,3,3)) # 2D 3*3 Matrix
np.zeros((2,3,3,3)) # Dimension, Matrix  number, Matrix Size

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [8]:
#All 1's Matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#Any other number Matrix
np.full((2,2),3) #Shape, number

array([[3, 3],
       [3, 3]])

In [14]:
#Any other number (full like)
np.full_like(array_one,4)
np.full(array_one.shape,5)

array([5, 5, 5])

In [17]:
#Generate random numbers between 0 and 1 (Decimal Values)
np.random.rand(4,3,2) # Number of Matrix, Row, Column
np.random.random_sample(array_one.shape) #if want to pass shape then have to use it

array([0.89840334, 0.80297345, 0.80577806])

In [18]:
#Generate random number of int 
np.random.randint(5, size=(3,3)) #number limit (excluded), size

array([[2, 1, 0],
       [2, 4, 1],
       [4, 0, 0]])

In [19]:
#Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
#Repeat an array
a= np.array([[1,2,3]])
r = np.repeat(a,3,axis=0) # repeated 3 times row
print(r)
r= np.repeat(a,3) # repeat in column , we can add axis=1 will do same
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 1 1 2 2 2 3 3 3]


# Creating a custom Matrix

In [34]:
array = np.ones((5,5))
array2= np.zeros((3,3))
array2[1,1]=9 # Replacing a specific element
array[1:4,1:4] = array2 # replacing within matrix with a matrix
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Careful when copying an matrix

In [37]:
a = np.array([1,2,3])
c = np.array([1,2,3]) 
b=a # If we write like this both matrix will point to the same array
b[0]=123
print(a)
b=c.copy() # this way it will creat a new array just like c
b[2] = 234
print(c)

[123   2   3]
[1 2 3]


## Mathematics

In [40]:
#Element wise addition, substraction, multiplication, division
a = np.array([1,2,3])
a = a + 2
print(a)

[3 4 5]


### Linear Algebra

In [41]:
# Matrix Multiplication
a = np.full((3,3),2)
b = np.full ((3,2),3)
np.matmul(a,b)

array([[18, 18],
       [18, 18],
       [18, 18]])

In [ ]:
#Determinant of a matrix
c = np.identity(3) 
np.linalg.det(c) #passing matrix must be an square matrix

## Statistics

In [49]:
#min & max of a matrix 
a = np.array([[1,2,3],[4,5,6]])
np.min(a)
np.max(a)

6

In [51]:
np.min(a, axis=1)

array([1, 4])

In [52]:
np.max(a,axis=1)

array([3, 6])

In [53]:
#Sum the total matrix
np.sum(a)

21

In [54]:
np.sum(a, axis=1) # Summing the matrix row wise

array([ 6, 15])

## Reorganizing Arrays

In [60]:
#Changing the shape of an array
#As long as dimensions are similar we are good

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [62]:
# VERICALLY, HORIZONTAL STACK
#dimensions are important here as well
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack([a,b])
print(c)
d = np.hstack([b,a])
print(d)

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8 1 2 3 4]


## Miscellaneous

#### Load data from file

filedata = np.genfromtext('text_file_name.txt', delimeter=',')
#convering float type to int

filedata.astype('int32')


#### Boolean Masking and Advance Indexing

In [64]:
a >3

array([False, False, False,  True])

In [65]:
a[a>3]

array([4])

In [68]:
((a>1) & (a<4))

array([False,  True,  True, False])

In [67]:
# Can index a list in numpy
x = np.array([1,2,3,4,5,6,7,8,9,10])
x[[1,2,-1]]

array([ 2,  3, 10])